apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: usecase1-placementrule
  namespace: usecase1-app
  labels:
    app: usecase1
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      env: dev