---
apiVersion: v1
kind: Namespace
metadata:
  name: usecase2-app
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: usecase2-app
  namespace: usecase2-app
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - usecase2-app
